version: '2'

services:

### Workspace Utilities Container ###########################

    # workspace:
    #     build:
    #         context: ./workspace
    #         args:
    #             - INSTALL_XDEBUG=false
    #             - INSTALL_MONGO=false
    #             - INSTALL_NODE=false
    #             - INSTALL_DRUSH=false
    #             - COMPOSER_GLOBAL_INSTALL=false
    #             - INSTALL_WORKSPACE_SSH=false
    #             - PUID=1000
    #             - PGID=1000
    #             - NODE_VERSION=stable
    #     volumes_from:
    #         - volumes_source
    #     extra_hosts:
    #         # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
    #         - "dockerhost:10.0.75.1"
    #     tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=true
            dockerfile: Dockerfile
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
            - "22:22"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=symfony.dev"
        links:
            - "mysql:local.mysql"

### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Nginx Server Container ##################################

    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

### symfony Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../my_framework:/var/www/symfony
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgres
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/sessions:/sessions
